### ISSUE TITLE
Transactions across repositories.

### ISSUE THREAD

**Issue by JamieCorkhill** [Melzar/onion-architecture-boilerplate#2]
Hello.

I quite like your repo. Suppose, in a given Service function, you wanted to make changes to multiple repositories within a transaction. How would you handle that while still abstracting away TypeORM?

Thank you.

**Comment by Melzar** [comment]
Hi, sorry for the late answer. I'm going to update this boilerplate soon and I haven't subscribed to any notifications :( but regarding your question - assuming that you would like to perform some operations within a single transaction, I would focus on infrastructure layer not services ( core layer ). Domain is not aware of data sources etc so we should keep transaction management in infrastructure layer - that's the first hint. Another hint is that any operations on given data source should happen in repositories ( as a given repository is bound to specific data source ). So making the story short I would consider a specific method for that where a given repository would implement it. I'll try to present it in upcoming update.

**Comment by Melzar** [comment]
Example is available in DbUserRepository - deleteUser method :) feel free to ask in case of any questions @JamieCorkhill. Closing issue

**Comment by JamieCorkhill** [comment]
I'll take a look. Thanks, @Melzar.
