### ISSUE TITLE
Propably Wrong Method Signature in EquipmentRepository

### ISSUE THREAD

**Issue by oliveirafilipe** [Melzar/onion-architecture-boilerplate#4]
Hi @Melzar, first: Your boilerplate is helping me a lot since it's my first deep dive in all those great architectural techniques.

I'm reading [hgraca's article](https://herbertograca.com/2017/11/16/explicit-architecture-01-ddd-hexagonal-onion-clean-cqrs-how-i-put-it-all-together/) while reading your code

I was going down trough the stack and found this method:

https://github.com/Melzar/onion-architecture-boilerplate/blob/0ec089c447fc9113b291dd2849053a3e916cca7c/src/core/applicationServices/Equipment/EquipmentService.ts#L17-L25

It is creating an `AddEquipmentRequest` to pass as parameter, but in the method definition:
https://github.com/Melzar/onion-architecture-boilerplate/blob/0ec089c447fc9113b291dd2849053a3e916cca7c/src/infrastructure/database/repository/EquipmentRepository.ts#L79-L82

It is expecting  `CreateEquipmentRequest`.

I know that both classes have the same signature:
https://github.com/Melzar/onion-architecture-boilerplate/blob/0ec089c447fc9113b291dd2849053a3e916cca7c/src/core/applicationServices/Equipment/requests/CreateEquipmentRequest.ts#L1-L3
https://github.com/Melzar/onion-architecture-boilerplate/blob/0ec089c447fc9113b291dd2849053a3e916cca7c/src/core/domainServices/Equipment/request/AddEquipmentRequest.ts#L1-L3

So, is `EquipmentRepository` class defining the wrong signature for `addEquipment` method or am i missing something?

Thank you!

**Comment by Melzar** [comment]
Sorry for late response - looks like my mistake, there should be `AddEquipmentRequest` in as argument in Repository method :). Thanks for catching that I'll provide small patch.

**Comment by Melzar** [comment]
@oliveirafilipe I've patched that method, I've also introduced a new pattern to the repository which affects this method. Enjoy and thank's for using this repo :)
